### ISSUE TITLE
Define metrics and alarms regarding "failed" measurements

### ISSUE THREAD

**Issue by hellais** [ooni/pipeline#137]
This entails:

* [ ] Defining how this metric looks like
* [ ] Adding to the pipeline documentation about this failed metric
* [ ] Defining a procedure for how these failed measurements should be handled

**Comment by darkk** [comment]
As it was [recently highlighted](https://github.com/ooni/pipeline/pull/177#discussion_r279317109) the pipeline works in _garbage-in-garbage-out_ mode trying to give a _best-effort_ service to incoming measurements.

That effectively means, that pipeline tries hard to ingest everything barely ingestable and takes a note if something went wrong. The places where the notes are taken are (at least) the following:
- `measurement.exc` column storing array of hashes of python exceptions happened during ingestion
- `measurement.residual_no` column storing a reference to `residual` table recording a weak "schema" of "unknown" json fields
- `measurement.msm_failure` that is currently unused, the idea was to mark measurement like #153 with this flag
- `badblob` table storing `badblob` records from `autoclaved/YYYY-MM-DD/index.json.gz`, that represent exceptions happening during _autoclaving_ stage
- `badmeta` table should store exceptions happening while ingesting very basic measurement metadata to `autoclaved`, `report` and `measurement` tables
- `badrow` stores record that PostgreSQL refuses to accept as a `COPY` input
- Airflow TaskInstance / DAG state, [e.g. there are some buckets from 2016](http://127.0.0.1:8080/admin/taskinstance/?flt0_dag_id_equals=hist_canning&flt1_state_equals=failed&flt4_task_id_equals=meta_pg) those are not ingested into PostgreSQL at all

_Ideally_ all of those records should be clean, that's the target for the metric, but code is imperfect. `badmeta` has no samples so far and it was the reason to introduce `FLAG_DEBUG_CHAOS` to debug that code path. Also, `badrow` table may deserve a patch that will record `bucket_date` as a part of a "bad row" to ease triaging (but it's rare error, so it did not happen so far). Also, Airflow sometimes fails to deliver expected logs via web-interface, so `find /srv -ipath '*/meta_pg/2016-02-23T00:00:00'` sometimes is the way to read logs at `datacollector.ingra.ooni.io`.

Here are few more lines on handling `measurement.exc` as an example.

The exceptions are accounted within the database itself as naive non-batched submission of exceptions to an external service (e.g. sentry) may slowdown ingestion and a single mistake during re-processing may lead to quota exhaustion. E.g. currently 45% of _all_ measurements are marked with exceptions (108m out of 240m). OTOH, only 0.5% of recent 2019Q1 measurements (0.1m out of 27m) are faulty in that sense.

The value that is stored is `exc_hash(sys.exc_info())`, upper 16 bits of the value represent the _traceback_ and the lower 16 bits represent the exception object. These values can be used to triage exceptions by "popularity" of exception, traceback or both. Let's take a look at bucket `2019-04-10` as an example:

```sql
select ehash, count(*) as cnt from (
    select (unnest(exc)) as ehash
    from autoclaved 
    join report using (autoclaved_no)
    join measurement using (report_no)
    where bucket_date = '2019-04-10' and exc is not null
) as t1 group by ehash order by cnt desc;

    ehash    | cnt 
-------------+-----
   763018621 | 1031
  1457421814 |  794
 -1115030883 |  403
  1463117099 |  295
 -1731042005 |  295
  -240599683 |  198
  1194527377 |   26
...
(17 rows)
```

Let's take 1457421814, it affects 51 different filenames out of 249 files in the 2019-04-10 bucket. Let's take for example `2019-04-10/web_connectivity.42.tar.lz4` and filter `index.json.gz` to keep only that file:

```sh
$ cd pipeline.git/af/shovel/autoclaved/2019-04-10
$ mv -n index.json.gz index.json.gz.orig
$ zcat index.json.gz.orig | .../trim_index.py 2019-04-10/web_connectivity.42.tar.lz4 | gzip >index.json.gz
```

So it'll give an exception:

```
$ OONI_FAIL_FAST=1 ./run-centrifugation 2019-04-10
...
measurement.id = fe58ce9c-89d9-4b7c-9e1c-f21e39a052c2
Traceback (most recent call last):
  File "./centrifugation.py", line 1767, in <module>
    main()
  File "./centrifugation.py", line 1764, in main
    meta_pg(opt.autoclaved_root, bucket, opt.postgres)
  File "./centrifugation.py", line 1717, in meta_pg
    copy_data_from_autoclaved(pgconn, stconn, in_root, bucket, bucket_code_ver)
  File "./centrifugation.py", line 634, in copy_data_from_autoclaved
    row = feeder.row(msm_no, datum)
  File "./centrifugation.py", line 1472, in row
    assert 'tor' not in r['request'] or not r['request']['tor']['is_tor']
KeyError: 'request'
```

And the following query will point to measurement:

```sql
select 'https://api.ooni.io/api/v1/measurement/temp-id-' || msm_no
from measurement where id = 'fe58ce9c-89d9-4b7c-9e1c-f21e39a052c2';
```

Or you can use mix of `tar`, `grep` and `jq` to look at it in CLI:
```
$ tar -x --to-stdout -I lz4 -f autoclaved/2019-04-10/web_connectivity.42.tar.lz4 | \
  grep -F fe58ce9c-89d9-4b7c-9e1c-f21e39a052c2 | jq . | less
```

[The measurement](https://api.ooni.io/api/v1/measurement/temp-id-290304334) has no `request` key in `.test_keys.requests[]`, although usually `web_connectivity` measurements have it even in case of connection failure, e.g. [`ce10626f-8d52-4246-8336-d08232cd2236`](https://api.ooni.io/api/v1/measurement/temp-id-32862886).

Is it a bug? Should this measurement be marked as faulty? Those are the questions to answer and to codify the decision as some code somewhere.

Afterwards the `autoclaved.file_sha1` can be updated with `digest('', 'sha1')` to force _reingestion_ for the corresponding files. _Reprocessing_ will not clear `exc` as it does not know the source of the exception and executes only subset of feeders, but reingestion will.

Alike procedure can be applied to other sorts of "failures" as well.
